module.exports={
  "data":{
   "name":"STATIONS",
   "entries":[
      {
         "value":"ABR",
         "synonyms":[
            "ABU ROAD",
            "ABR"
         ]
      },
      {
         "value":"ADB",
         "synonyms":[
            "ADILABAD",
            "ADB"
         ]
      },
      {
         "value":"AD",
         "synonyms":[
            "ADONI",
            "AD"
         ]
      },
      {
         "value":"ADRA",
         "synonyms":[
            "ADRA",
            "ADRA"
         ]
      },
      {
         "value":"AGTL",
         "synonyms":[
            "AGARTALA",
            "AGTL"
         ]
      },
      {
         "value":"AF",
         "synonyms":[
            "AGRA FORT",
            "AF"
         ]
      },
      {
         "value":"AGC",
         "synonyms":[
            "AGRA CANTT",
            "AGC"
         ]
      },
      {
         "value":"ANG",
         "synonyms":[
            "AHMADNAGAR",
            "ANG"
         ]
      },
      {
         "value":"ADI",
         "synonyms":[
            "AHMEDABAD",
            "ADI"
         ]
      },
      {
         "value":"AII",
         "synonyms":[
            "AJMER",
            "AII"
         ]
      },
      {
         "value":"AJNI",
         "synonyms":[
            "AJUNCTIONI",
            "AJNI",
            "AJNI"
         ]
      },
      {
         "value":"AK",
         "synonyms":[
            "AKOLA",
            "AK"
         ]
      },
      {
         "value":"ALJN",
         "synonyms":[
            "ALIGARH",
            "ALJN"
         ]
      },
      {
         "value":"APDJ",
         "synonyms":[
            "ALIPURDUAR JUNCTION",
            "ALIPURDUAR JN",
            "APDJ"
         ]
      },
      {
         "value":"ALD",
         "synonyms":[
            "ALLAHABAD",
            "ALD"
         ]
      },
      {
         "value":"ALLP",
         "synonyms":[
            "ALAPPUZHA",
            "ALLP"
         ]
      },
      {
         "value":"LWR",
         "synonyms":[
            "ALNAWAR JUNCTION",
            "ALNAWAR JN",
            "LWR"
         ]
      },
      {
         "value":"AWY",
         "synonyms":[
            "ALUVA",
            "AWY"
         ]
      },
      {
         "value":"AWR",
         "synonyms":[
            "ALWAR",
            "AWR"
         ]
      },
      {
         "value":"AN",
         "synonyms":[
            "AMALNER",
            "AN"
         ]
      },
      {
         "value":"AADR",
         "synonyms":[
            "AMB ANDAVRA",
            "AADR"
         ]
      },
      {
         "value":"UMB",
         "synonyms":[
            "AMBALA CANTT",
            "UMB"
         ]
      },
      {
         "value":"ABKP",
         "synonyms":[
            "AMBIKAPUR",
            "ABKP"
         ]
      },
      {
         "value":"AMLA",
         "synonyms":[
            "AMLA",
            "AMLA"
         ]
      },
      {
         "value":"ASR",
         "synonyms":[
            "AMRITSAR",
            "ASR"
         ]
      },
      {
         "value":"AKP",
         "synonyms":[
            "ANAKAPALLE",
            "AKP"
         ]
      },
      {
         "value":"ANND",
         "synonyms":[
            "ANAND",
            "ANND"
         ]
      },
      {
         "value":"ANDN",
         "synonyms":[
            "ANAND NAGAR",
            "ANDN"
         ]
      },
      {
         "value":"ANVT",
         "synonyms":[
            "ANAND VIHAR TERMINUS",
            "ANVT"
         ]
      },
      {
         "value":"ATP",
         "synonyms":[
            "ANANTAPUR",
            "ATP"
         ]
      },
      {
         "value":"ANGL",
         "synonyms":[
            "ANGUL",
            "ANGL"
         ]
      },
      {
         "value":"ANV",
         "synonyms":[
            "ANNAVARAM",
            "ANV"
         ]
      },
      {
         "value":"APR",
         "synonyms":[
            "ANUPPUR",
            "APR"
         ]
      },
      {
         "value":"ARA",
         "synonyms":[
            "ARA",
            "ARA"
         ]
      },
      {
         "value":"AJJ",
         "synonyms":[
            "ARAKKONAM",
            "AJJ"
         ]
      },
      {
         "value":"ASK",
         "synonyms":[
            "ARSIKERE",
            "ASK"
         ]
      },
      {
         "value":"ASN",
         "synonyms":[
            "ASANSOL",
            "ASN"
         ]
      },
      {
         "value":"ARJ",
         "synonyms":[
            "AUNRIHAR",
            "ARJ"
         ]
      },
      {
         "value":"AWB",
         "synonyms":[
            "AURANGABAD",
            "AWB"
         ]
      },
      {
         "value":"AY",
         "synonyms":[
            "AYODHYA",
            "AY"
         ]
      },
      {
         "value":"AMH",
         "synonyms":[
            "AZAMGARH",
            "AMH"
         ]
      },
      {
         "value":"AZ",
         "synonyms":[
            "AZIMGANJ JUNCTION",
            "AZIMGANJ JN",
            "AZ"
         ]
      },
      {
         "value":"BPB",
         "synonyms":[
            "BADARPUR",
            "BPB"
         ]
      },
      {
         "value":"BD",
         "synonyms":[
            "BADNERA JUNCTION",
            "BADNERA JN",
            "BD"
         ]
      },
      {
         "value":"BGK",
         "synonyms":[
            "BAGALKOT",
            "BGK"
         ]
      },
      {
         "value":"BPM",
         "synonyms":[
            "BAGHPAT ROAD",
            "BPM"
         ]
      },
      {
         "value":"BDME",
         "synonyms":[
            "BAIDYANATHDHAM",
            "BDME"
         ]
      },
      {
         "value":"BKP",
         "synonyms":[
            "BAKTHIYARPUR",
            "BKP"
         ]
      },
      {
         "value":"BLS",
         "synonyms":[
            "BALASORE",
            "BLS"
         ]
      },
      {
         "value":"BTC",
         "synonyms":[
            "BALAGHAT",
            "BTC"
         ]
      },
      {
         "value":"BLGR",
         "synonyms":[
            "BALANGIR",
            "BLGR"
         ]
      },
      {
         "value":"BALU",
         "synonyms":[
            "BALUGAON",
            "BALU"
         ]
      },
      {
         "value":"BLGT",
         "synonyms":[
            "BALURGHAT",
            "BLGT"
         ]
      },
      {
         "value":"BPQ",
         "synonyms":[
            "BALHARSHAH",
            "BPQ"
         ]
      },
      {
         "value":"BUI",
         "synonyms":[
            "BALLIA",
            "BUI"
         ]
      },
      {
         "value":"BNQ",
         "synonyms":[
            "BANARHAT",
            "BNQ"
         ]
      },
      {
         "value":"BNDA",
         "synonyms":[
            "BANDA JUNCTION",
            "BANDA JN",
            "BNDA"
         ]
      },
      {
         "value":"BDC",
         "synonyms":[
            "BANDEL JUNCTION",
            "BANDEL JN",
            "BDC"
         ]
      },
      {
         "value":"BKI",
         "synonyms":[
            "BANDIKUI JUNCTION",
            "BANDIKUI JN",
            "BKI"
         ]
      },
      {
         "value":"BDTS",
         "synonyms":[
            "BANDRA",
            "BDTS"
         ]
      },
      {
         "value":"SBC",
         "synonyms":[
            "BANGALORE CITY",
            "SBC"
         ]
      },
      {
         "value":"BNC",
         "synonyms":[
            "BANGALORE CANTT",
            "BNC"
         ]
      },
      {
         "value":"BWT",
         "synonyms":[
            "BANGARAPET",
            "BWT"
         ]
      },
      {
         "value":"BGY",
         "synonyms":[
            "BANGRIPOSI",
            "BGY"
         ]
      },
      {
         "value":"BQA",
         "synonyms":[
            "BANKURA",
            "BQA"
         ]
      },
      {
         "value":"BNKI",
         "synonyms":[
            "BANMANKHI",
            "BNKI"
         ]
      },
      {
         "value":"BPP",
         "synonyms":[
            "BAPATLA",
            "BPP"
         ]
      },
      {
         "value":"BBK",
         "synonyms":[
            "BARABANKI JUNCTION",
            "BARABANKI JN",
            "BBK"
         ]
      },
      {
         "value":"BBN",
         "synonyms":[
            "BARABIL",
            "BBN"
         ]
      },
      {
         "value":"BAZ",
         "synonyms":[
            "BARAN",
            "BAZ"
         ]
      },
      {
         "value":"BJU",
         "synonyms":[
            "BARAUNI JUNCTION",
            "BARAUNI JN",
            "BJU"
         ]
      },
      {
         "value":"BTU",
         "synonyms":[
            "BARAUT",
            "BTU"
         ]
      },
      {
         "value":"BRPL",
         "synonyms":[
            "BARAPALLI",
            "BRPL"
         ]
      },
      {
         "value":"BWN",
         "synonyms":[
            "BARDDHAMAN JUNCTION",
            "BARDDHAMAN JN",
            "BWN"
         ]
      },
      {
         "value":"BE",
         "synonyms":[
            "BAREILLY",
            "BE"
         ]
      },
      {
         "value":"BRGA",
         "synonyms":[
            "BARGARH ROAD",
            "BRGA"
         ]
      },
      {
         "value":"BNY",
         "synonyms":[
            "BARHNI",
            "BNY"
         ]
      },
      {
         "value":"BRKA",
         "synonyms":[
            "BARKAKANA",
            "BRKA"
         ]
      },
      {
         "value":"BME",
         "synonyms":[
            "BARMER",
            "BME"
         ]
      },
      {
         "value":"BOF",
         "synonyms":[
            "BAROG",
            "BOF"
         ]
      },
      {
         "value":"BOE",
         "synonyms":[
            "BARSOI",
            "BOE"
         ]
      },
      {
         "value":"BRWD",
         "synonyms":[
            "BARWADIH",
            "BRWD"
         ]
      },
      {
         "value":"BSX",
         "synonyms":[
            "BASAR",
            "BSX"
         ]
      },
      {
         "value":"BST",
         "synonyms":[
            "BASTI",
            "BST"
         ]
      },
      {
         "value":"BTI",
         "synonyms":[
            "BATHINDA JUNCTION",
            "BATHINDA JN",
            "BTI"
         ]
      },
      {
         "value":"BXN",
         "synonyms":[
            "BAYANA",
            "BXN"
         ]
      },
      {
         "value":"BEAS",
         "synonyms":[
            "BEAS",
            "BEAS"
         ]
      },
      {
         "value":"BER",
         "synonyms":[
            "BEAWAR",
            "BER"
         ]
      },
      {
         "value":"BAP",
         "synonyms":[
            "BELAPUR",
            "BAP"
         ]
      },
      {
         "value":"BGM",
         "synonyms":[
            "BELGAUM",
            "BGM"
         ]
      },
      {
         "value":"BAY",
         "synonyms":[
            "BELLARY JUNCTION",
            "BELLARY JN",
            "BAY"
         ]
      },
      {
         "value":"BTH",
         "synonyms":[
            "BETTIAH",
            "BTH"
         ]
      },
      {
         "value":"BZU",
         "synonyms":[
            "BETUL",
            "BZU"
         ]
      },
      {
         "value":"BOY",
         "synonyms":[
            "BHADOHI",
            "BOY"
         ]
      },
      {
         "value":"BHC",
         "synonyms":[
            "BHADRAK",
            "BHC"
         ]
      },
      {
         "value":"BGP",
         "synonyms":[
            "BHAGALPUR",
            "BGP"
         ]
      },
      {
         "value":"BGKI",
         "synonyms":[
            "BHAGAT KI KOTHI",
            "BGKI"
         ]
      },
      {
         "value":"BTE",
         "synonyms":[
            "BHARATPUR",
            "BTE"
         ]
      },
      {
         "value":"BH",
         "synonyms":[
            "BHARUCH",
            "BH"
         ]
      },
      {
         "value":"BYT",
         "synonyms":[
            "BHATAPARA",
            "BYT"
         ]
      },
      {
         "value":"BTJL",
         "synonyms":[
            "BHATKAL",
            "BTJL"
         ]
      },
      {
         "value":"BTT",
         "synonyms":[
            "BHATNI",
            "BTT"
         ]
      },
      {
         "value":"BVC",
         "synonyms":[
            "BHAVNAGAR",
            "BVC"
         ]
      },
      {
         "value":"BWPI",
         "synonyms":[
            "BHAWANIPATNA",
            "BWPI"
         ]
      },
      {
         "value":"BHL",
         "synonyms":[
            "BHILWARA",
            "BHL"
         ]
      },
      {
         "value":"BVRM",
         "synonyms":[
            "BHIMAVARAM JUNCTION",
            "BHIMAVARAM JN",
            "BVRM"
         ]
      },
      {
         "value":"BVRT",
         "synonyms":[
            "BHIMAVARAM TOWN",
            "BVRT"
         ]
      },
      {
         "value":"BIX",
         "synonyms":[
            "BHIND",
            "BIX"
         ]
      },
      {
         "value":"BNW",
         "synonyms":[
            "BHIWANI",
            "BNW"
         ]
      },
      {
         "value":"BPL",
         "synonyms":[
            "BHOPAL",
            "BPL"
         ]
      },
      {
         "value":"BBS",
         "synonyms":[
            "BHUBANESWAR",
            "BBS"
         ]
      },
      {
         "value":"BHUJ",
         "synonyms":[
            "BHUJ",
            "BHUJ"
         ]
      },
      {
         "value":"BSL",
         "synonyms":[
            "BHUSAVAL",
            "BSL"
         ]
      },
      {
         "value":"BJP",
         "synonyms":[
            "BIJAPUR",
            "BJP"
         ]
      },
      {
         "value":"BJO",
         "synonyms":[
            "BIJUNCTIONOR",
            "BIJNOR",
            "BJO"
         ]
      },
      {
         "value":"BKN",
         "synonyms":[
            "BIKANER",
            "BKN"
         ]
      },
      {
         "value":"BSP",
         "synonyms":[
            "BILASPUR JUNCTION",
            "BILASPUR JN",
            "BSP"
         ]
      },
      {
         "value":"BINA",
         "synonyms":[
            "BINA",
            "BINA"
         ]
      },
      {
         "value":"BNV",
         "synonyms":[
            "BINNAGURI",
            "BNV"
         ]
      },
      {
         "value":"RRB",
         "synonyms":[
            "BIRUR",
            "RRB"
         ]
      },
      {
         "value":"BTTR",
         "synonyms":[
            "BITRAGUNTA",
            "BTTR"
         ]
      },
      {
         "value":"BRRG",
         "synonyms":[
            "BIYAVARA RAJGARH",
            "BRRG"
         ]
      },
      {
         "value":"VBL",
         "synonyms":[
            "BOBBILI",
            "VBL"
         ]
      },
      {
         "value":"BONA",
         "synonyms":[
            "BOINDA",
            "BONA"
         ]
      },
      {
         "value":"BRPL",
         "synonyms":[
            "BARAPALLI",
            "BRPL"
         ]
      },
      {
         "value":"BGBR",
         "synonyms":[
            "BAGHBAHAR",
            "BGBR"
         ]
      },
      {
         "value":"BKSC",
         "synonyms":[
            "BOKARO STEEL CITY",
            "BKSC"
         ]
      },
      {
         "value":"BHP",
         "synonyms":[
            "BOLPUR SHANTINIKETAN",
            "BHP"
         ]
      },
      {
         "value":"BVI",
         "synonyms":[
            "BORIVALI",
            "BVI"
         ]
      },
      {
         "value":"BTD",
         "synonyms":[
            "BOTAD",
            "BTD"
         ]
      },
      {
         "value":"BEM",
         "synonyms":[
            "BUDAUN",
            "BEM"
         ]
      },
      {
         "value":"BUDI",
         "synonyms":[
            "BUNDI",
            "BUDI"
         ]
      },
      {
         "value":"BAU",
         "synonyms":[
            "BURHANPUR",
            "BAU"
         ]
      },
      {
         "value":"BUW",
         "synonyms":[
            "BURHWAL",
            "BUW"
         ]
      },
      {
         "value":"BXR",
         "synonyms":[
            "BUXAR",
            "BXR"
         ]
      },
      {
         "value":"CNO",
         "synonyms":[
            "CANACONA",
            "CNO"
         ]
      },
      {
         "value":"CAA",
         "synonyms":[
            "CHAKIA",
            "CAA"
         ]
      },
      {
         "value":"CHKB",
         "synonyms":[
            "CHAKKI BANK",
            "CHKB"
         ]
      },
      {
         "value":"CKP",
         "synonyms":[
            "CHAKRADHARPUR",
            "CKP"
         ]
      },
      {
         "value":"CSN",
         "synonyms":[
            "CHALISGAON",
            "CSN"
         ]
      },
      {
         "value":"CPH",
         "synonyms":[
            "CHAMPA",
            "CPH"
         ]
      },
      {
         "value":"CH",
         "synonyms":[
            "CHANDAUSI",
            "CH"
         ]
      },
      {
         "value":"CNA",
         "synonyms":[
            "CHANDERIYA",
            "CNA"
         ]
      },
      {
         "value":"CDG",
         "synonyms":[
            "CHANDIGARH",
            "CDG"
         ]
      },
      {
         "value":"CNI",
         "synonyms":[
            "CHANDIL",
            "CNI"
         ]
      },
      {
         "value":"CD",
         "synonyms":[
            "CHANDRAPUR",
            "CD"
         ]
      },
      {
         "value":"CRP",
         "synonyms":[
            "CHANDRAPURA",
            "CRP"
         ]
      },
      {
         "value":"CPK",
         "synonyms":[
            "CHAPARMUKH",
            "CPK"
         ]
      },
      {
         "value":"CAP",
         "synonyms":[
            "CHATRAPUR",
            "CAP"
         ]
      },
      {
         "value":"CGL",
         "synonyms":[
            "CHENGALPATTU JUNCTION",
            "CHENGALPATTU JN",
            "CGL"
         ]
      },
      {
         "value":"CNGR",
         "synonyms":[
            "CHENGANNUR",
            "CNGR"
         ]
      },
      {
         "value":"MAS",
         "synonyms":[
            "CHENNAI CENTRAL",
            "MAS"
         ]
      },
      {
         "value":"MS",
         "synonyms":[
            "CHENNAI EGMORE",
            "MS"
         ]
      },
      {
         "value":"CPR",
         "synonyms":[
            "CHHAPRA",
            "CPR"
         ]
      },
      {
         "value":"CWA",
         "synonyms":[
            "CHHINDWARA",
            "CWA"
         ]
      },
      {
         "value":"CDM",
         "synonyms":[
            "CHIDAMBARAM",
            "CDM"
         ]
      },
      {
         "value":"JRU",
         "synonyms":[
            "CHIKJAJUR",
            "JRU"
         ]
      },
      {
         "value":"CHI",
         "synonyms":[
            "CHIPLUN",
            "CHI"
         ]
      },
      {
         "value":"CLX",
         "synonyms":[
            "CHIRALA",
            "CLX"
         ]
      },
      {
         "value":"CKTD",
         "synonyms":[
            "CHITRAKOOTDHAM KARVI",
            "CKTD"
         ]
      },
      {
         "value":"CRJ",
         "synonyms":[
            "CHITTARANJAN",
            "CRJ"
         ]
      },
      {
         "value":"COR",
         "synonyms":[
            "CHITTAURGARH",
            "COR"
         ]
      },
      {
         "value":"CTO",
         "synonyms":[
            "CHITTOOR",
            "CTO"
         ]
      },
      {
         "value":"CPU",
         "synonyms":[
            "CHOPAN",
            "CPU"
         ]
      },
      {
         "value":"CAR",
         "synonyms":[
            "CHUNAR",
            "CAR"
         ]
      },
      {
         "value":"CUR",
         "synonyms":[
            "CHURU",
            "CUR"
         ]
      },
      {
         "value":"CBE",
         "synonyms":[
            "COIMBATORE JUNCTION",
            "COIMBATORE JN",
            "CBE"
         ]
      },
      {
         "value":"ONR",
         "synonyms":[
            "COONOOR",
            "ONR"
         ]
      },
      {
         "value":"CUPJ",
         "synonyms":[
            "CUDDALORE PORT",
            "CUPJ"
         ]
      },
      {
         "value":"HX",
         "synonyms":[
            "CUDDAPAH",
            "HX"
         ]
      },
      {
         "value":"CTC",
         "synonyms":[
            "CUTTACK",
            "CTC"
         ]
      },
      {
         "value":"DR",
         "synonyms":[
            "DADAR",
            "DR"
         ]
      },
      {
         "value":"DRD",
         "synonyms":[
            "DAHANU ROAD",
            "DRD"
         ]
      },
      {
         "value":"DHD",
         "synonyms":[
            "DAHOD",
            "DHD"
         ]
      },
      {
         "value":"DLO",
         "synonyms":[
            "DALGAON",
            "DLO"
         ]
      },
      {
         "value":"DTO",
         "synonyms":[
            "DALTONGANJ",
            "DTO"
         ]
      },
      {
         "value":"DRZ",
         "synonyms":[
            "DALLIRAJHARA",
            "DRZ"
         ]
      },
      {
         "value":"DMO",
         "synonyms":[
            "DAMOH",
            "DMO"
         ]
      },
      {
         "value":"DNR",
         "synonyms":[
            "DANAPUR",
            "DNR"
         ]
      },
      {
         "value":"DBG",
         "synonyms":[
            "DARBHANGA",
            "DBG"
         ]
      },
      {
         "value":"DD",
         "synonyms":[
            "DAUND",
            "DD"
         ]
      },
      {
         "value":"DVG",
         "synonyms":[
            "DAVANGERE",
            "DVG"
         ]
      },
      {
         "value":"DDN",
         "synonyms":[
            "DEHRADUN",
            "DDN"
         ]
      },
      {
         "value":"DOS",
         "synonyms":[
            "DEHRI-ON-SONE",
            "DOS"
         ]
      },
      {
         "value":"DLI",
         "synonyms":[
            "DELHI",
            "DLI"
         ]
      },
      {
         "value":"NDLS",
         "synonyms":[
            "NEW DELHI",
            "NDLS"
         ]
      },
      {
         "value":"DEC",
         "synonyms":[
            "DELHI CANTT",
            "DEC"
         ]
      },
      {
         "value":"DEE",
         "synonyms":[
            "DELHI SARAI ROHILLA",
            "DEE"
         ]
      },
      {
         "value":"DSA",
         "synonyms":[
            "DELHI SHAHDARA",
            "DSA"
         ]
      },
      {
         "value":"DEOS",
         "synonyms":[
            "DEORIASADAR",
            "DEOS"
         ]
      },
      {
         "value":"DVL",
         "synonyms":[
            "DEVLALI",
            "DVL"
         ]
      },
      {
         "value":"DMN",
         "synonyms":[
            "DHAMANGAON",
            "DMN"
         ]
      },
      {
         "value":"DHN",
         "synonyms":[
            "DHANBAD",
            "DHN"
         ]
      },
      {
         "value":"DAB",
         "synonyms":[
            "DHARMABAD",
            "DAB"
         ]
      },
      {
         "value":"DMR",
         "synonyms":[
            "DHARMANAGAR",
            "DMR"
         ]
      },
      {
         "value":"DPJ",
         "synonyms":[
            "DHARMAPURI",
            "DPJ"
         ]
      },
      {
         "value":"DMM",
         "synonyms":[
            "DHARMAVARAM",
            "DMM"
         ]
      },
      {
         "value":"DWR",
         "synonyms":[
            "DHARWAD",
            "DWR"
         ]
      },
      {
         "value":"DAS",
         "synonyms":[
            "DHASA",
            "DAS"
         ]
      },
      {
         "value":"DHO",
         "synonyms":[
            "DHAULPUR",
            "DHO"
         ]
      },
      {
         "value":"DNUL",
         "synonyms":[
            "DHENUANAL",
            "DNUL"
         ]
      },
      {
         "value":"DLJ",
         "synonyms":[
            "DHOLA",
            "DLJ"
         ]
      },
      {
         "value":"DHNE",
         "synonyms":[
            "DHONE",
            "DHNE"
         ]
      },
      {
         "value":"DHG",
         "synonyms":[
            "DHRANGADHRA",
            "DHG"
         ]
      },
      {
         "value":"DBB",
         "synonyms":[
            "DHUBRI",
            "DBB"
         ]
      },
      {
         "value":"DUI",
         "synonyms":[
            "DHURI",
            "DUI"
         ]
      },
      {
         "value":"DBRG",
         "synonyms":[
            "DIBRUGARH",
            "DBRG"
         ]
      },
      {
         "value":"DBRT",
         "synonyms":[
            "DIBRUGARH TOWN",
            "DBRT"
         ]
      },
      {
         "value":"DGHA",
         "synonyms":[
            "DIGHA",
            "DGHA"
         ]
      },
      {
         "value":"DLN",
         "synonyms":[
            "DILDARNAGAR",
            "DLN"
         ]
      },
      {
         "value":"DMV",
         "synonyms":[
            "DIMAPUR",
            "DMV"
         ]
      },
      {
         "value":"DG",
         "synonyms":[
            "DINDIGUL JUNCTION",
            "DINDIGUL JN",
            "DG"
         ]
      },
      {
         "value":"DGG",
         "synonyms":[
            "DONGARGARH",
            "DGG"
         ]
      },
      {
         "value":"DKJ",
         "synonyms":[
            "DORNAKAL",
            "DKJ"
         ]
      },
      {
         "value":"DNRP",
         "synonyms":[
            "DUNGARPUR",
            "DNRP"
         ]
      },
      {
         "value":"DURG",
         "synonyms":[
            "DURG",
            "DURG"
         ]
      },
      {
         "value":"DGR",
         "synonyms":[
            "DURGAPUR",
            "DGR"
         ]
      },
      {
         "value":"DVD",
         "synonyms":[
            "DUVVADA",
            "DVD"
         ]
      },
      {
         "value":"DWK",
         "synonyms":[
            "DWARKA",
            "DWK"
         ]
      },
      {
         "value":"EE",
         "synonyms":[
            "ELURU",
            "EE"
         ]
      },
      {
         "value":"ERS",
         "synonyms":[
            "ERNAKULAM JUNCTION",
            "ERNAKULAM JN",
            "ERS"
         ]
      },
      {
         "value":"ERN",
         "synonyms":[
            "ERNAKULAM TOWN",
            "ERN"
         ]
      },
      {
         "value":"ED",
         "synonyms":[
            "ERODE",
            "ED"
         ]
      },
      {
         "value":"ETW",
         "synonyms":[
            "ETAWAH",
            "ETW"
         ]
      },
      {
         "value":"FD",
         "synonyms":[
            "FAIZABAD",
            "FD"
         ]
      },
      {
         "value":"FDB",
         "synonyms":[
            "FARIDABAD",
            "FDB"
         ]
      },
      {
         "value":"FBD",
         "synonyms":[
            "FARRUKHABAD",
            "FBD"
         ]
      },
      {
         "value":"FTD",
         "synonyms":[
            "FATEHABAD CHAND",
            "FTD"
         ]
      },
      {
         "value":"FTP",
         "synonyms":[
            "FATEHPUR",
            "FTP"
         ]
      },
      {
         "value":"FUT",
         "synonyms":[
            "FATUHA",
            "FUT"
         ]
      },
      {
         "value":"FKA",
         "synonyms":[
            "FAZILKA",
            "FKA"
         ]
      },
      {
         "value":"FZD",
         "synonyms":[
            "FIROZABAD",
            "FZD"
         ]
      },
      {
         "value":"FZP",
         "synonyms":[
            "FIROZPUR CITY",
            "FZP"
         ]
      },
      {
         "value":"FZR",
         "synonyms":[
            "FIROZPUR CANTT",
            "FZR"
         ]
      },
      {
         "value":"FBG",
         "synonyms":[
            "FORBESGANJ",
            "FBG"
         ]
      },
      {
         "value":"FKG",
         "synonyms":[
            "FURKATING",
            "FKG"
         ]
      },
      {
         "value":"GDG",
         "synonyms":[
            "GADAG",
            "GDG"
         ]
      },
      {
         "value":"GJL",
         "synonyms":[
            "GAJRAULA",
            "GJL"
         ]
      },
      {
         "value":"GIM",
         "synonyms":[
            "GANDHIDHAM",
            "GIM"
         ]
      },
      {
         "value":"GADJ",
         "synonyms":[
            "GANDHINAGAR",
            "GADJ"
         ]
      },
      {
         "value":"GGC",
         "synonyms":[
            "GANGAPUR CITY",
            "GGC"
         ]
      },
      {
         "value":"GHD",
         "synonyms":[
            "GARWA ROAD",
            "GHD"
         ]
      },
      {
         "value":"GAYA",
         "synonyms":[
            "GAYA",
            "GAYA"
         ]
      },
      {
         "value":"GAD",
         "synonyms":[
            "GEVRA ROAD",
            "GAD"
         ]
      },
      {
         "value":"GTS",
         "synonyms":[
            "GHATSILA",
            "GTS"
         ]
      },
      {
         "value":"GZB",
         "synonyms":[
            "GHAZIABAD",
            "GZB"
         ]
      },
      {
         "value":"GLPT",
         "synonyms":[
            "GOALPARA TOWN",
            "GLPT"
         ]
      },
      {
         "value":"GDA",
         "synonyms":[
            "GODHRA",
            "GDA"
         ]
      },
      {
         "value":"GK",
         "synonyms":[
            "GOLA GOKARANNATH",
            "GK"
         ]
      },
      {
         "value":"GD",
         "synonyms":[
            "GONDA",
            "GD"
         ]
      },
      {
         "value":"G",
         "synonyms":[
            "GONDIA",
            "G"
         ]
      },
      {
         "value":"GY",
         "synonyms":[
            "GOOTY",
            "GY"
         ]
      },
      {
         "value":"GKP",
         "synonyms":[
            "GORAKHPUR",
            "GKP"
         ]
      },
      {
         "value":"GOGH",
         "synonyms":[
            "GOSSAINGAON HAT",
            "GOGH"
         ]
      },
      {
         "value":"GDV",
         "synonyms":[
            "GUDIVADA",
            "GDV"
         ]
      },
      {
         "value":"GDR",
         "synonyms":[
            "GUDUR",
            "GDR"
         ]
      },
      {
         "value":"GR",
         "synonyms":[
            "GULBARGA",
            "GR"
         ]
      },
      {
         "value":"GUNA",
         "synonyms":[
            "GUNA",
            "GUNA"
         ]
      },
      {
         "value":"GTL",
         "synonyms":[
            "GUNTAKAL",
            "GTL"
         ]
      },
      {
         "value":"GNT",
         "synonyms":[
            "GUNTUR",
            "GNT"
         ]
      },
      {
         "value":"GGN",
         "synonyms":[
            "GURGAON",
            "GGN"
         ]
      },
      {
         "value":"GUV",
         "synonyms":[
            "GURUVAYUR",
            "GUV"
         ]
      },
      {
         "value":"GHY",
         "synonyms":[
            "GUWAHATI",
            "GHY"
         ]
      },
      {
         "value":"GWL",
         "synonyms":[
            "GWALIOR",
            "GWL"
         ]
      },
      {
         "value":"GYN",
         "synonyms":[
            "GYANPUR ROAD",
            "GYN"
         ]
      },
      {
         "value":"HBJ",
         "synonyms":[
            "HABIBGANJ",
            "HBJ"
         ]
      },
      {
         "value":"HJP",
         "synonyms":[
            "HAJIPUR",
            "HJP"
         ]
      },
      {
         "value":"HLZ",
         "synonyms":[
            "HALDIA",
            "HLZ"
         ]
      },
      {
         "value":"HDB",
         "synonyms":[
            "HALDIBARI",
            "HDB"
         ]
      },
      {
         "value":"HOJ",
         "synonyms":[
            "HAMILTONGANJ",
            "HOJ"
         ]
      },
      {
         "value":"HMH",
         "synonyms":[
            "HANUMANGARH",
            "HMH"
         ]
      },
      {
         "value":"HAPA",
         "synonyms":[
            "HAPA",
            "HAPA"
         ]
      },
      {
         "value":"HPU",
         "synonyms":[
            "HAPUR",
            "HPU"
         ]
      },
      {
         "value":"HD",
         "synonyms":[
            "HARDA",
            "HD"
         ]
      },
      {
         "value":"HW",
         "synonyms":[
            "HARIDWAR",
            "HW"
         ]
      },
      {
         "value":"HRR",
         "synonyms":[
            "HARIHAR",
            "HRR"
         ]
      },
      {
         "value":"HPP",
         "synonyms":[
            "HARPALPUR",
            "HPP"
         ]
      },
      {
         "value":"HSA",
         "synonyms":[
            "HASIMARA",
            "HSA"
         ]
      },
      {
         "value":"HTE",
         "synonyms":[
            "HATIA",
            "HTE"
         ]
      },
      {
         "value":"NED",
         "synonyms":[
            "HAZUR SAHIB NANDED",
            "NED"
         ]
      },
      {
         "value":"HIL",
         "synonyms":[
            "HILSA",
            "HIL"
         ]
      },
      {
         "value":"HMT",
         "synonyms":[
            "HIMMAT NAGAR",
            "HMT"
         ]
      },
      {
         "value":"HUP",
         "synonyms":[
            "HINDUPUR",
            "HUP"
         ]
      },
      {
         "value":"HNL",
         "synonyms":[
            "HINGOLI",
            "HNL"
         ]
      },
      {
         "value":"HSR",
         "synonyms":[
            "HISAR",
            "HSR"
         ]
      },
      {
         "value":"HBD",
         "synonyms":[
            "HOSHANGABAD",
            "HBD"
         ]
      },
      {
         "value":"HPT",
         "synonyms":[
            "HOSPET",
            "HPT"
         ]
      },
      {
         "value":"HSRA",
         "synonyms":[
            "HOSUR",
            "HSRA"
         ]
      },
      {
         "value":"HBG",
         "synonyms":[
            "HOWBADH",
            "HBG"
         ]
      },
      {
         "value":"HWH",
         "synonyms":[
            "HOWRAH",
            "HWH"
         ]
      },
      {
         "value":"UBL",
         "synonyms":[
            "HUBLI",
            "UBL"
         ]
      },
      {
         "value":"HYB",
         "synonyms":[
            "HYDERABAD",
            "HYB"
         ]
      },
      {
         "value":"IGP",
         "synonyms":[
            "IGATPURI",
            "IGP"
         ]
      },
      {
         "value":"IAA",
         "synonyms":[
            "INDARA",
            "IAA"
         ]
      },
      {
         "value":"INDB",
         "synonyms":[
            "INDORE",
            "INDB"
         ]
      },
      {
         "value":"IPR",
         "synonyms":[
            "ISLAMPUR",
            "IPR"
         ]
      },
      {
         "value":"ET",
         "synonyms":[
            "ITARSI",
            "ET"
         ]
      },
      {
         "value":"JBP",
         "synonyms":[
            "JABALPUR",
            "JBP"
         ]
      },
      {
         "value":"JDB",
         "synonyms":[
            "JAGDALPUR",
            "JDB"
         ]
      },
      {
         "value":"JP",
         "synonyms":[
            "JAIPUR",
            "JP"
         ]
      },
      {
         "value":"JYP",
         "synonyms":[
            "JAYPUR",
            "JYP"
         ]
      },
      {
         "value":"JSM",
         "synonyms":[
            "JAISALMER",
            "JSM"
         ]
      },
      {
         "value":"JJKR",
         "synonyms":[
            "JAJPUR KEONJHAR ROAD",
            "JJKR"
         ]
      },
      {
         "value":"JHL",
         "synonyms":[
            "JAKHAL",
            "JHL"
         ]
      },
      {
         "value":"JM",
         "synonyms":[
            "JALAMB",
            "JM"
         ]
      },
      {
         "value":"JRC",
         "synonyms":[
            "JALANDHAR CANTT",
            "JRC"
         ]
      },
      {
         "value":"JUC",
         "synonyms":[
            "JALANDHAR CITY",
            "JUC"
         ]
      },
      {
         "value":"JL",
         "synonyms":[
            "JALGAON",
            "JL"
         ]
      },
      {
         "value":"J",
         "synonyms":[
            "JALNA",
            "J"
         ]
      },
      {
         "value":"JPG",
         "synonyms":[
            "JALPAIGURI",
            "JPG"
         ]
      },
      {
         "value":"JMP",
         "synonyms":[
            "JAMALPUR",
            "JMP"
         ]
      },
      {
         "value":"JAT",
         "synonyms":[
            "JAMMU TAWI",
            "JAT"
         ]
      },
      {
         "value":"JAM",
         "synonyms":[
            "JAMNAGAR",
            "JAM"
         ]
      },
      {
         "value":"JNH",
         "synonyms":[
            "JANGHAI",
            "JNH"
         ]
      },
      {
         "value":"JSME",
         "synonyms":[
            "JASIDIH",
            "JSME"
         ]
      },
      {
         "value":"JNU",
         "synonyms":[
            "JAUNPUR JUNCTION",
            "JAUNPUR JN",
            "JNU"
         ]
      },
      {
         "value":"JYG",
         "synonyms":[
            "JAYNAGAR",
            "JYG"
         ]
      },
      {
         "value":"JLR",
         "synonyms":[
            "JETALSAR",
            "JLR"
         ]
      },
      {
         "value":"JAJ",
         "synonyms":[
            "JHAJHA",
            "JAJ"
         ]
      },
      {
         "value":"JHS",
         "synonyms":[
            "JHANSI",
            "JHS"
         ]
      },
      {
         "value":"JGM",
         "synonyms":[
            "JHARGRAM",
            "JGM"
         ]
      },
      {
         "value":"JSG",
         "synonyms":[
            "JHARSUGUDA",
            "JSG"
         ]
      },
      {
         "value":"JIND",
         "synonyms":[
            "JIND",
            "JIND"
         ]
      },
      {
         "value":"JU",
         "synonyms":[
            "JODHPUR",
            "JU"
         ]
      },
      {
         "value":"JBN",
         "synonyms":[
            "JOGBANI",
            "JBN"
         ]
      },
      {
         "value":"JTJ",
         "synonyms":[
            "JOLARPETTAI",
            "JTJ"
         ]
      },
      {
         "value":"JT",
         "synonyms":[
            "JORHAT",
            "JT"
         ]
      },
      {
         "value":"JND",
         "synonyms":[
            "JUNAGARH JUNCTION.",
            "JUNAGARH JN.",
            "JND"
         ]
      },
      {
         "value":"KCG",
         "synonyms":[
            "KACHEGUDA",
            "KCG"
         ]
      },
      {
         "value":"COA",
         "synonyms":[
            "KAKINADA PORT",
            "COA"
         ]
      },
      {
         "value":"KCF",
         "synonyms":[
            "KALCHINI",
            "KCF"
         ]
      },
      {
         "value":"KLK",
         "synonyms":[
            "KALKA",
            "KLK"
         ]
      },
      {
         "value":"KLL",
         "synonyms":[
            "KALOL",
            "KLL"
         ]
      },
      {
         "value":"KYN",
         "synonyms":[
            "KALYAN",
            "KYN"
         ]
      },
      {
         "value":"KYQ",
         "synonyms":[
            "KAMAKHYA",
            "KYQ"
         ]
      },
      {
         "value":"CJ",
         "synonyms":[
            "KANCHIPURAM",
            "CJ"
         ]
      },
      {
         "value":"KQL",
         "synonyms":[
            "KANDHLA",
            "KQL"
         ]
      },
      {
         "value":"CAPE",
         "synonyms":[
            "KANNIYAKUMARI",
            "CAPE"
         ]
      },
      {
         "value":"CAN",
         "synonyms":[
            "KANNUR",
            "CAN"
         ]
      },
      {
         "value":"CNB",
         "synonyms":[
            "KANPUR CENTRAL",
            "CNB"
         ]
      },
      {
         "value":"CPA",
         "synonyms":[
            "KANPUR ANWARGANJ",
            "CPA"
         ]
      },
      {
         "value":"CPJ",
         "synonyms":[
            "KAPTANGANJ",
            "CPJ"
         ]
      },
      {
         "value":"KIK",
         "synonyms":[
            "KARAIKAL",
            "KIK"
         ]
      },
      {
         "value":"KKDI",
         "synonyms":[
            "KARAIKKUDI JUNCTION",
            "KARAIKKUDI JN",
            "KKDI"
         ]
      },
      {
         "value":"KXJ",
         "synonyms":[
            "KARIMGANJ",
            "KXJ"
         ]
      },
      {
         "value":"KUN",
         "synonyms":[
            "KARNAL",
            "KUN"
         ]
      },
      {
         "value":"KRR",
         "synonyms":[
            "KARUR",
            "KRR"
         ]
      },
      {
         "value":"KAWR",
         "synonyms":[
            "KARWAR",
            "KAWR"
         ]
      },
      {
         "value":"KGQ",
         "synonyms":[
            "KASARAGOD",
            "KGQ"
         ]
      },
      {
         "value":"KSJ",
         "synonyms":[
            "KASGANJ",
            "KSJ"
         ]
      },
      {
         "value":"KGM",
         "synonyms":[
            "KATHGODAM",
            "KGM"
         ]
      },
      {
         "value":"KIR",
         "synonyms":[
            "KATIHAR",
            "KIR"
         ]
      },
      {
         "value":"KTE",
         "synonyms":[
            "KATNI",
            "KTE"
         ]
      },
      {
         "value":"KMZ",
         "synonyms":[
            "KATNI MURWARA",
            "KMZ"
         ]
      },
      {
         "value":"KPD",
         "synonyms":[
            "KATPADI",
            "KPD"
         ]
      },
      {
         "value":"KWAE",
         "synonyms":[
            "KATWA",
            "KWAE"
         ]
      },
      {
         "value":"KZJ",
         "synonyms":[
            "KAZIPET",
            "KZJ"
         ]
      },
      {
         "value":"KSNG",
         "synonyms":[
            "KESINGA",
            "KSNG"
         ]
      },
      {
         "value":"KDJR",
         "synonyms":[
            "KENDUJHARGARH",
            "KDJR"
         ]
      },
      {
         "value":"KGG",
         "synonyms":[
            "KHAGARIA",
            "KGG"
         ]
      },
      {
         "value":"KLD",
         "synonyms":[
            "KHALILABAD",
            "KLD"
         ]
      },
      {
         "value":"KMT",
         "synonyms":[
            "KHAMMAM",
            "KMT"
         ]
      },
      {
         "value":"KNW",
         "synonyms":[
            "KHANDWA",
            "KNW"
         ]
      },
      {
         "value":"KGP",
         "synonyms":[
            "KHARAGPUR",
            "KGP"
         ]
      },
      {
         "value":"KEX",
         "synonyms":[
            "KHEKRA",
            "KEX"
         ]
      },
      {
         "value":"KUR",
         "synonyms":[
            "KHURDA ROAD",
            "KUR"
         ]
      },
      {
         "value":"KRJ",
         "synonyms":[
            "KHURJA",
            "KRJ"
         ]
      },
      {
         "value":"KNE",
         "synonyms":[
            "KISHANGANJ",
            "KNE"
         ]
      },
      {
         "value":"KSG",
         "synonyms":[
            "KISHANGARH",
            "KSG"
         ]
      },
      {
         "value":"KIUL",
         "synonyms":[
            "KIUL",
            "KIUL"
         ]
      },
      {
         "value":"KCVL",
         "synonyms":[
            "KOCHUVELI",
            "KCVL"
         ]
      },
      {
         "value":"KQN",
         "synonyms":[
            "KODAIKANAL ROAD",
            "KQN"
         ]
      },
      {
         "value":"KOAA",
         "synonyms":[
            "KOLKATA",
            "KOAA"
         ]
      },
      {
         "value":"QLN",
         "synonyms":[
            "KOLLAM",
            "QLN"
         ]
      },
      {
         "value":"KPG",
         "synonyms":[
            "KOPERGAON",
            "KPG"
         ]
      },
      {
         "value":"KRPU",
         "synonyms":[
            "KORAPUT",
            "KRPU"
         ]
      },
      {
         "value":"KRBA",
         "synonyms":[
            "KORBA",
            "KRBA"
         ]
      },
      {
         "value":"KOTA",
         "synonyms":[
            "KOTA",
            "KOTA"
         ]
      },
      {
         "value":"KTW",
         "synonyms":[
            "KOTDWARA",
            "KTW"
         ]
      },
      {
         "value":"KKP",
         "synonyms":[
            "KOT KAPURA",
            "KKP"
         ]
      },
      {
         "value":"KTYM",
         "synonyms":[
            "KOTTAYAM",
            "KTYM"
         ]
      },
      {
         "value":"CLT",
         "synonyms":[
            "KOZHIKODE",
            "CLT"
         ]
      },
      {
         "value":"KNJ",
         "synonyms":[
            "KRISHNANAGAR CITY",
            "KNJ"
         ]
      },
      {
         "value":"KJM",
         "synonyms":[
            "KRISHNARAJAPURAM",
            "KJM"
         ]
      },
      {
         "value":"KUGT",
         "synonyms":[
            "KUMARGHAT",
            "KUGT"
         ]
      },
      {
         "value":"KMU",
         "synonyms":[
            "KUMBAKONAM",
            "KMU"
         ]
      },
      {
         "value":"KUDA",
         "synonyms":[
            "KUNDAPURA",
            "KUDA"
         ]
      },
      {
         "value":"KWV",
         "synonyms":[
            "KURDUWADI",
            "KWV"
         ]
      },
      {
         "value":"KRNT",
         "synonyms":[
            "KURNOOL TOWN",
            "KRNT"
         ]
      },
      {
         "value":"KKDE",
         "synonyms":[
            "KURUKSHETRA",
            "KKDE"
         ]
      },
      {
         "value":"LMP",
         "synonyms":[
            "LAKHIMPUR",
            "LMP"
         ]
      },
      {
         "value":"LRJ",
         "synonyms":[
            "LAKSAR",
            "LRJ"
         ]
      },
      {
         "value":"LGH",
         "synonyms":[
            "LALGARH",
            "LGH"
         ]
      },
      {
         "value":"LGL",
         "synonyms":[
            "LALGOLA",
            "LGL"
         ]
      },
      {
         "value":"LAR",
         "synonyms":[
            "LALITPUR",
            "LAR"
         ]
      },
      {
         "value":"LKU",
         "synonyms":[
            "LALKUAN JUNCTION",
            "LALKUAN JN",
            "LKU"
         ]
      },
      {
         "value":"LUR",
         "synonyms":[
            "LATUR",
            "LUR"
         ]
      },
      {
         "value":"LEDO",
         "synonyms":[
            "LEDO",
            "LEDO"
         ]
      },
      {
         "value":"LHU",
         "synonyms":[
            "LOHARU",
            "LHU"
         ]
      },
      {
         "value":"LTT",
         "synonyms":[
            "LOKMANYA TILAK",
            "LTT"
         ]
      },
      {
         "value":"LNL",
         "synonyms":[
            "LONAVLA",
            "LNL"
         ]
      },
      {
         "value":"LD",
         "synonyms":[
            "LONDA",
            "LD"
         ]
      },
      {
         "value":"LFG",
         "synonyms":[
            "LOWER HALFLONG",
            "LFG"
         ]
      },
      {
         "value":"LJN/LKO",
         "synonyms":[
            "LUCKNOW",
            "LJN/LKO"
         ]
      },
      {
         "value":"LDH",
         "synonyms":[
            "LUDHIANA",
            "LDH"
         ]
      },
      {
         "value":"LMG",
         "synonyms":[
            "LUMDING",
            "LMG"
         ]
      },
      {
         "value":"LUNI",
         "synonyms":[
            "LUNI",
            "LUNI"
         ]
      },
      {
         "value":"MTM",
         "synonyms":[
            "MACHILIPATNAM",
            "MTM"
         ]
      },
      {
         "value":"MDT",
         "synonyms":[
            "MADARIHAT",
            "MDT"
         ]
      },
      {
         "value":"MAD",
         "synonyms":[
            "MADDUR",
            "MAD"
         ]
      },
      {
         "value":"MAO",
         "synonyms":[
            "MADGAON",
            "MAO"
         ]
      },
      {
         "value":"MBI",
         "synonyms":[
            "MADHUBANI",
            "MBI"
         ]
      },
      {
         "value":"MDP",
         "synonyms":[
            "MADHUPUR",
            "MDP"
         ]
      },
      {
         "value":"MDU",
         "synonyms":[
            "MADURAI JUNCTION",
            "MADURAI JN",
            "MDU"
         ]
      },
      {
         "value":"MSMD",
         "synonyms":[
            "MAHASAMUND",
            "MSMD"
         ]
      },
      {
         "value":"MBNR",
         "synonyms":[
            "MAHBUBNAGAR",
            "MBNR"
         ]
      },
      {
         "value":"MHV",
         "synonyms":[
            "MAHUVA",
            "MHV"
         ]
      },
      {
         "value":"MNGD",
         "synonyms":[
            "MUNIGUDA",
            "MNGD"
         ]
      },
      {
         "value":"MSH",
         "synonyms":[
            "MAHESANA",
            "MSH"
         ]
      },
      {
         "value":"MBA",
         "synonyms":[
            "MAHOBA",
            "MBA"
         ]
      },
      {
         "value":"MLN",
         "synonyms":[
            "MAILANI",
            "MLN"
         ]
      },
      {
         "value":"MKC",
         "synonyms":[
            "MAKSI",
            "MKC"
         ]
      },
      {
         "value":"MLDT",
         "synonyms":[
            "MALDA TOWN",
            "MLDT"
         ]
      },
      {
         "value":"MNM",
         "synonyms":[
            "MANAMADURAI",
            "MNM"
         ]
      },
      {
         "value":"MUV",
         "synonyms":[
            "MANDUADIH",
            "MUV"
         ]
      },
      {
         "value":"MAQ",
         "synonyms":[
            "MANGALORE CENTRAL",
            "MAQ"
         ]
      },
      {
         "value":"MAJN",
         "synonyms":[
            "MANGALORE JUNCTION",
            "MANGALORE JN",
            "MAJN"
         ]
      },
      {
         "value":"MKP",
         "synonyms":[
            "MANIKPUR",
            "MKP"
         ]
      },
      {
         "value":"MUR",
         "synonyms":[
            "MANKAPUR",
            "MUR"
         ]
      },
      {
         "value":"MMR",
         "synonyms":[
            "MANMAD",
            "MMR"
         ]
      },
      {
         "value":"MQ",
         "synonyms":[
            "MANNARGUDI",
            "MQ"
         ]
      },
      {
         "value":"MNE",
         "synonyms":[
            "MANSI",
            "MNE"
         ]
      },
      {
         "value":"MANU",
         "synonyms":[
            "MANU",
            "MANU"
         ]
      },
      {
         "value":"MXN",
         "synonyms":[
            "MARIANI",
            "MXN"
         ]
      },
      {
         "value":"MJ",
         "synonyms":[
            "MARWAR JUNCTION",
            "MARWAR JN",
            "MJ"
         ]
      },
      {
         "value":"MTJ",
         "synonyms":[
            "MATHURA",
            "MTJ"
         ]
      },
      {
         "value":"MAU",
         "synonyms":[
            "MAU",
            "MAU"
         ]
      },
      {
         "value":"MV",
         "synonyms":[
            "MAYILADUTURAI JUNCTION",
            "MAYILADUTURAI JN",
            "MV"
         ]
      },
      {
         "value":"MTC",
         "synonyms":[
            "MEERUT CITY",
            "MTC"
         ]
      },
      {
         "value":"MTD",
         "synonyms":[
            "MERTA ROAD",
            "MTD"
         ]
      },
      {
         "value":"MTP",
         "synonyms":[
            "METTUPALAYAM",
            "MTP"
         ]
      },
      {
         "value":"MDN",
         "synonyms":[
            "MIDNAPORE",
            "MDN"
         ]
      },
      {
         "value":"MRJ",
         "synonyms":[
            "MIRAJ",
            "MRJ"
         ]
      },
      {
         "value":"MRGA",
         "synonyms":[
            "MIRYALAGUDA",
            "MRGA"
         ]
      },
      {
         "value":"MZP",
         "synonyms":[
            "MIRZAPUR",
            "MZP"
         ]
      },
      {
         "value":"MOF",
         "synonyms":[
            "MOGA",
            "MOF"
         ]
      },
      {
         "value":"MKA",
         "synonyms":[
            "MOKAMA",
            "MKA"
         ]
      },
      {
         "value":"PDKT",
         "synonyms":[
            "PUDUKOTTAI",
            "PDKT"
         ]
      },
      {
         "value":"PLO",
         "synonyms":[
            "PULGAON",
            "PLO"
         ]
      },
      {
         "value":"PUNE",
         "synonyms":[
            "PUNE JUNCTION",
            "PUNE JN",
            "PUNE"
         ]
      },
      {
         "value":"PP",
         "synonyms":[
            "PURANPUR",
            "PP"
         ]
      },
      {
         "value":"PURI",
         "synonyms":[
            "PURI",
            "PURI"
         ]
      },
      {
         "value":"PAU",
         "synonyms":[
            "PURNA",
            "PAU"
         ]
      },
      {
         "value":"PRNA",
         "synonyms":[
            "PURNIA",
            "PRNA"
         ]
      },
      {
         "value":"PRR",
         "synonyms":[
            "PURULIA",
            "PRR"
         ]
      },
      {
         "value":"RDP",
         "synonyms":[
            "RADHIKAPUR",
            "RDP"
         ]
      },
      {
         "value":"RBL",
         "synonyms":[
            "RAE BARELI",
            "RBL"
         ]
      },
      {
         "value":"RC",
         "synonyms":[
            "RAICHUR",
            "RC"
         ]
      },
      {
         "value":"RIG",
         "synonyms":[
            "RAIGARH",
            "RIG"
         ]
      },
      {
         "value":"R",
         "synonyms":[
            "RAIPUR",
            "R"
         ]
      },
      {
         "value":"RJY",
         "synonyms":[
            "RAJAHMUNDRY",
            "RJY"
         ]
      },
      {
         "value":"RJK",
         "synonyms":[
            "RAJA KA SAHASPUR",
            "RJK"
         ]
      },
      {
         "value":"RKM",
         "synonyms":[
            "RAJA KI MANDI",
            "RKM"
         ]
      },
      {
         "value":"RJQ",
         "synonyms":[
            "RAJENDRANAGAR",
            "RJQ"
         ]
      },
      {
         "value":"RGD",
         "synonyms":[
            "RAJGIR",
            "RGD"
         ]
      },
      {
         "value":"RJT",
         "synonyms":[
            "RAJKOT",
            "RJT"
         ]
      },
      {
         "value":"RJN",
         "synonyms":[
            "RAJUNCTIONANDGAON",
            "RAJNANDGAON",
            "RJN"
         ]
      },
      {
         "value":"RPJ",
         "synonyms":[
            "RAJPURA",
            "RPJ"
         ]
      },
      {
         "value":"RDM",
         "synonyms":[
            "RAMAGUNDAM",
            "RDM"
         ]
      },
      {
         "value":"RMD",
         "synonyms":[
            "RAMANATHAPURAM",
            "RMD"
         ]
      },
      {
         "value":"RMM",
         "synonyms":[
            "RAMESWARAM",
            "RMM"
         ]
      },
      {
         "value":"RMR",
         "synonyms":[
            "RAMNAGAR",
            "RMR"
         ]
      },
      {
         "value":"RMU",
         "synonyms":[
            "RAMPUR JUNCTION",
            "RAMPUR JN",
            "RMU"
         ]
      },
      {
         "value":"RPH",
         "synonyms":[
            "RAMPURHAT",
            "RPH"
         ]
      },
      {
         "value":"RHA",
         "synonyms":[
            "RANAGHAT",
            "RHA"
         ]
      },
      {
         "value":"RNC",
         "synonyms":[
            "RANCHI",
            "RNC"
         ]
      },
      {
         "value":"RPAN",
         "synonyms":[
            "RANGAPARA NORTH",
            "RPAN"
         ]
      },
      {
         "value":"RNY",
         "synonyms":[
            "RANGIYA",
            "RNY"
         ]
      },
      {
         "value":"ROJ",
         "synonyms":[
            "RANINAGAR",
            "ROJ"
         ]
      },
      {
         "value":"RTGH",
         "synonyms":[
            "RATANGARH",
            "RTGH"
         ]
      },
      {
         "value":"RTM",
         "synonyms":[
            "RATLAM",
            "RTM"
         ]
      },
      {
         "value":"RN",
         "synonyms":[
            "RATNAGIRI",
            "RN"
         ]
      },
      {
         "value":"RJ",
         "synonyms":[
            "RAWATGANJ",
            "RJ"
         ]
      },
      {
         "value":"RXL",
         "synonyms":[
            "RAXAUL",
            "RXL"
         ]
      },
      {
         "value":"RGDA",
         "synonyms":[
            "RAYAGADA",
            "RGDA"
         ]
      },
      {
         "value":"RU",
         "synonyms":[
            "RENIGUNTA",
            "RU"
         ]
      },
      {
         "value":"REWA",
         "synonyms":[
            "REWA",
            "REWA"
         ]
      },
      {
         "value":"RE",
         "synonyms":[
            "REWARI",
            "RE"
         ]
      },
      {
         "value":"RGS",
         "synonyms":[
            "RINGUS",
            "RGS"
         ]
      },
      {
         "value":"ROK",
         "synonyms":[
            "ROHTAK",
            "ROK"
         ]
      },
      {
         "value":"RK",
         "synonyms":[
            "ROORKEE",
            "RK"
         ]
      },
      {
         "value":"ROU",
         "synonyms":[
            "ROURKELA",
            "ROU"
         ]
      },
      {
         "value":"SDLP",
         "synonyms":[
            "SADULPUR",
            "SDLP"
         ]
      },
      {
         "value":"SRF",
         "synonyms":[
            "SAGAR JAMBAGARU",
            "SRF"
         ]
      },
      {
         "value":"SGL",
         "synonyms":[
            "SAGAULI",
            "SGL"
         ]
      },
      {
         "value":"SGO",
         "synonyms":[
            "SAGOUR",
            "SGO"
         ]
      },
      {
         "value":"SRE",
         "synonyms":[
            "SAHARANPUR",
            "SRE"
         ]
      },
      {
         "value":"SHC",
         "synonyms":[
            "SAHARSA",
            "SHC"
         ]
      },
      {
         "value":"SBG",
         "synonyms":[
            "SAHIBGANJ",
            "SBG"
         ]
      },
      {
         "value":"SNSI",
         "synonyms":[
            "SAI NAGAR SHIRDI",
            "SNSI"
         ]
      },
      {
         "value":"SA",
         "synonyms":[
            "SALEM",
            "SA"
         ]
      },
      {
         "value":"SRU",
         "synonyms":[
            "SALEMPUR",
            "SRU"
         ]
      },
      {
         "value":"SLO",
         "synonyms":[
            "SAMALKOT",
            "SLO"
         ]
      },
      {
         "value":"SPJ",
         "synonyms":[
            "SAMASTIPUR",
            "SPJ"
         ]
      },
      {
         "value":"SBP",
         "synonyms":[
            "SAMBALPUR",
            "SBP"
         ]
      },
      {
         "value":"SBPY",
         "synonyms":[
            "SAMBALPUR CITY",
            "SBPY"
         ]
      },
      {
         "value":"SMR",
         "synonyms":[
            "SAMDARI",
            "SMR"
         ]
      },
      {
         "value":"AMTA",
         "synonyms":[
            "SAMUKTALA ROAD",
            "AMTA"
         ]
      },
      {
         "value":"SLI",
         "synonyms":[
            "SANGLI",
            "SLI"
         ]
      },
      {
         "value":"SRC",
         "synonyms":[
            "SANTRAGACHI",
            "SRC"
         ]
      },
      {
         "value":"SRNT",
         "synonyms":[
            "SARNATH",
            "SRNT"
         ]
      },
      {
         "value":"STR",
         "synonyms":[
            "SATARA",
            "STR"
         ]
      },
      {
         "value":"STA",
         "synonyms":[
            "SATNA",
            "STA"
         ]
      },
      {
         "value":"SAP",
         "synonyms":[
            "SATTENAPALLE",
            "SAP"
         ]
      },
      {
         "value":"SWM",
         "synonyms":[
            "SAWAIMADHOPUR",
            "SWM"
         ]
      },
      {
         "value":"SWV",
         "synonyms":[
            "SAWANTWADI ROAD",
            "SWV"
         ]
      },
      {
         "value":"SDAH",
         "synonyms":[
            "SEALDAH",
            "SDAH"
         ]
      },
      {
         "value":"SC",
         "synonyms":[
            "SECUNDERABAD",
            "SC"
         ]
      },
      {
         "value":"SCT",
         "synonyms":[
            "SENGOTTAI",
            "SCT"
         ]
      },
      {
         "value":"SCF",
         "synonyms":[
            "SENSOA",
            "SCF"
         ]
      },
      {
         "value":"SEGM",
         "synonyms":[
            "SEWAGRAM",
            "SEGM"
         ]
      },
      {
         "value":"SDB",
         "synonyms":[
            "SHAHABAD",
            "SDB"
         ]
      },
      {
         "value":"SHG",
         "synonyms":[
            "SHAHGANJ",
            "SHG"
         ]
      },
      {
         "value":"SPN",
         "synonyms":[
            "SHAHJAHANPUR",
            "SPN"
         ]
      },
      {
         "value":"SPP",
         "synonyms":[
            "SHAHPUR PATOREE",
            "SPP"
         ]
      },
      {
         "value":"SKTN",
         "synonyms":[
            "SHAKTINAGAR",
            "SKTN"
         ]
      },
      {
         "value":"SHM",
         "synonyms":[
            "SHALIMAR",
            "SHM"
         ]
      },
      {
         "value":"SGZ",
         "synonyms":[
            "SHAMGARH",
            "SGZ"
         ]
      },
      {
         "value":"SMQL",
         "synonyms":[
            "SHAMLI",
            "SMQL"
         ]
      },
      {
         "value":"SKB",
         "synonyms":[
            "SHIKOHABAD",
            "SKB"
         ]
      },
      {
         "value":"SML",
         "synonyms":[
            "SHIMLA",
            "SML"
         ]
      },
      {
         "value":"SMET",
         "synonyms":[
            "SHIMOGA TOWN",
            "SMET"
         ]
      },
      {
         "value":"SVPI",
         "synonyms":[
            "SHIVPURI",
            "SVPI"
         ]
      },
      {
         "value":"SRR",
         "synonyms":[
            "SHORANUR JUNCTION",
            "SHORANUR JN",
            "SRR"
         ]
      },
      {
         "value":"SMBJ",
         "synonyms":[
            "SHRI MAHABIRJI",
            "SMBJ"
         ]
      },
      {
         "value":"SOJN",
         "synonyms":[
            "SIHOR GUJARAT",
            "SOJN"
         ]
      },
      {
         "value":"SIKR",
         "synonyms":[
            "SIKAR",
            "SIKR"
         ]
      },
      {
         "value":"MB",
         "synonyms":[
            "MORADABAD",
            "MB"
         ]
      },
      {
         "value":"MKI",
         "synonyms":[
            "MOTIHARI",
            "MKI"
         ]
      },
      {
         "value":"MUE",
         "synonyms":[
            "MUDKHED",
            "MUE"
         ]
      },
      {
         "value":"MGS",
         "synonyms":[
            "MUGHALSARAI",
            "MGS"
         ]
      },
      {
         "value":"BCT",
         "synonyms":[
            "MUMBAI CENTRAL",
            "BCT"
         ]
      },
      {
         "value":"CSTM",
         "synonyms":[
            "MUMBAI CST",
            "CSTM"
         ]
      },
      {
         "value":"MNGD",
         "synonyms":[
            "MUNIGUDA",
            "MNGD"
         ]
      },
      {
         "value":"MURI",
         "synonyms":[
            "MURI",
            "MURI"
         ]
      },
      {
         "value":"MZS",
         "synonyms":[
            "MURKEONGSELEK",
            "MZS"
         ]
      },
      {
         "value":"MZR",
         "synonyms":[
            "MURTAJAPUR",
            "MZR"
         ]
      },
      {
         "value":"MOZ",
         "synonyms":[
            "MUZAFFAR NAGAR",
            "MOZ"
         ]
      },
      {
         "value":"MFP",
         "synonyms":[
            "MUZAFFARPUR",
            "MFP"
         ]
      },
      {
         "value":"MYS",
         "synonyms":[
            "MYSORE",
            "MYS"
         ]
      },
      {
         "value":"NDAE",
         "synonyms":[
            "NABADWIPDHAM",
            "NDAE"
         ]
      },
      {
         "value":"ND",
         "synonyms":[
            "NADIAD",
            "ND"
         ]
      },
      {
         "value":"NDKD",
         "synonyms":[
            "NADIKUDI",
            "NDKD"
         ]
      },
      {
         "value":"NGT",
         "synonyms":[
            "NAGAPPATTINAM",
            "NGT"
         ]
      },
      {
         "value":"NKB",
         "synonyms":[
            "NAGARKATA",
            "NKB"
         ]
      },
      {
         "value":"NSL",
         "synonyms":[
            "NAGARSOL",
            "NSL"
         ]
      },
      {
         "value":"NAB",
         "synonyms":[
            "NAGBHIR",
            "NAB"
         ]
      },
      {
         "value":"NAD",
         "synonyms":[
            "NAGDA",
            "NAD"
         ]
      },
      {
         "value":"NCJ",
         "synonyms":[
            "NAGERCOIL JUNCTION",
            "NAGERCOIL JN",
            "NCJ"
         ]
      },
      {
         "value":"NCR",
         "synonyms":[
            "NAGORE",
            "NCR"
         ]
      },
      {
         "value":"NGP",
         "synonyms":[
            "NAGPUR",
            "NGP"
         ]
      },
      {
         "value":"NKB",
         "synonyms":[
            "NAGRAKATA",
            "NKB"
         ]
      },
      {
         "value":"NIR",
         "synonyms":[
            "NAINPUR",
            "NIR"
         ]
      },
      {
         "value":"NBD",
         "synonyms":[
            "NAJIBABAD",
            "NBD"
         ]
      },
      {
         "value":"NLD",
         "synonyms":[
            "NALANDA",
            "NLD"
         ]
      },
      {
         "value":"NLDA",
         "synonyms":[
            "NALGONDA",
            "NLDA"
         ]
      },
      {
         "value":"NMKL",
         "synonyms":[
            "NAMAKKAL",
            "NMKL"
         ]
      },
      {
         "value":"NRE",
         "synonyms":[
            "NANDALUR",
            "NRE"
         ]
      },
      {
         "value":"NGN",
         "synonyms":[
            "NANDGAON",
            "NGN"
         ]
      },
      {
         "value":"NDB",
         "synonyms":[
            "NANDURBAR",
            "NDB"
         ]
      },
      {
         "value":"NDL",
         "synonyms":[
            "NANDYAL",
            "NDL"
         ]
      },
      {
         "value":"NLDM",
         "synonyms":[
            "NANGAL DAM",
            "NLDM"
         ]
      },
      {
         "value":"NKE",
         "synonyms":[
            "NARKATIAGANJ",
            "NKE"
         ]
      },
      {
         "value":"NS",
         "synonyms":[
            "NARASAPUR",
            "NS"
         ]
      },
      {
         "value":"NU",
         "synonyms":[
            "NARSINGPUR",
            "NU"
         ]
      },
      {
         "value":"NRW",
         "synonyms":[
            "NARWANA",
            "NRW"
         ]
      },
      {
         "value":"NK",
         "synonyms":[
            "NASIK ROAD",
            "NK"
         ]
      },
      {
         "value":"NUH",
         "synonyms":[
            "NAUGARH",
            "NUH"
         ]
      },
      {
         "value":"NLR",
         "synonyms":[
            "NELLORE",
            "NLR"
         ]
      },
      {
         "value":"NOQ",
         "synonyms":[
            "NEW ALIPURDUAR",
            "NOQ"
         ]
      },
      {
         "value":"NBQ",
         "synonyms":[
            "NEW BONGAIGAON",
            "NBQ"
         ]
      },
      {
         "value":"NCB",
         "synonyms":[
            "NEW COOCHBEHAR",
            "NCB"
         ]
      },
      {
         "value":"NDLS",
         "synonyms":[
            "NEW DELHI",
            "NDLS"
         ]
      },
      {
         "value":"NFK",
         "synonyms":[
            "NEW FARAKKA",
            "NFK"
         ]
      },
      {
         "value":"NJP",
         "synonyms":[
            "NEW JALPAIGURI",
            "NJP"
         ]
      },
      {
         "value":"NMZ",
         "synonyms":[
            "NEWMAL JUNCTION",
            "NEWMAL JN",
            "NMZ"
         ]
      },
      {
         "value":"NTSK",
         "synonyms":[
            "NEW TINSUKIA",
            "NTSK"
         ]
      },
      {
         "value":"NDD",
         "synonyms":[
            "NIDADAVOLU",
            "NDD"
         ]
      },
      {
         "value":"NMJ",
         "synonyms":[
            "NIDAMANGALAM",
            "NMJ"
         ]
      },
      {
         "value":"NDO",
         "synonyms":[
            "NIDUBROLU",
            "NDO"
         ]
      },
      {
         "value":"NMH",
         "synonyms":[
            "NIMACH",
            "NMH"
         ]
      },
      {
         "value":"NZB",
         "synonyms":[
            "NIZAMABAD",
            "NZB"
         ]
      },
      {
         "value":"NZM",
         "synonyms":[
            "NIZAMUDDIN",
            "NZM"
         ]
      },
      {
         "value":"NOLI",
         "synonyms":[
            "NOLI",
            "NOLI"
         ]
      },
      {
         "value":"NLP",
         "synonyms":[
            "NORTH LAKHIMPUR",
            "NLP"
         ]
      },
      {
         "value":"ODB",
         "synonyms":[
            "ODLABARI",
            "ODB"
         ]
      },
      {
         "value":"OKHA",
         "synonyms":[
            "OKHA",
            "OKHA"
         ]
      },
      {
         "value":"OGL",
         "synonyms":[
            "ONGOLE",
            "OGL"
         ]
      },
      {
         "value":"ORAI",
         "synonyms":[
            "ORAI",
            "ORAI"
         ]
      },
      {
         "value":"PC",
         "synonyms":[
            "PACHORA",
            "PC"
         ]
      },
      {
         "value":"PLNI",
         "synonyms":[
            "PALANI",
            "PLNI"
         ]
      },
      {
         "value":"PNU",
         "synonyms":[
            "PALANPUR",
            "PNU"
         ]
      },
      {
         "value":"PSA",
         "synonyms":[
            "PALASA",
            "PSA"
         ]
      },
      {
         "value":"PGT",
         "synonyms":[
            "PALAKKAD",
            "PGT"
         ]
      },
      {
         "value":"PGTN",
         "synonyms":[
            "PALAKKAD TOWN",
            "PGTN"
         ]
      },
      {
         "value":"PLK",
         "synonyms":[
            "PALIAKALAN",
            "PLK"
         ]
      },
      {
         "value":"PVR",
         "synonyms":[
            "PANDHARAPUR",
            "PVR"
         ]
      },
      {
         "value":"PNP",
         "synonyms":[
            "PANIPAT",
            "PNP"
         ]
      },
      {
         "value":"PRDP",
         "synonyms":[
            "PARADEEP",
            "PRDP"
         ]
      },
      {
         "value":"PNME",
         "synonyms":[
            "PARASNATH",
            "PNME"
         ]
      },
      {
         "value":"PNVL",
         "synonyms":[
            "PANVEL",
            "PNVL"
         ]
      },
      {
         "value":"PBN",
         "synonyms":[
            "PARBHANI",
            "PBN"
         ]
      },
      {
         "value":"PVPT",
         "synonyms":[
            "PARVATIPURAM TOWN",
            "PVPT"
         ]
      },
      {
         "value":"PTK",
         "synonyms":[
            "PATHANKOT",
            "PTK"
         ]
      },
      {
         "value":"PTA",
         "synonyms":[
            "PATIALA",
            "PTA"
         ]
      },
      {
         "value":"PNBE",
         "synonyms":[
            "PATNA",
            "PNBE"
         ]
      },
      {
         "value":"PNC",
         "synonyms":[
            "PATNA SAHIB",
            "PNC"
         ]
      },
      {
         "value":"PLC",
         "synonyms":[
            "PHALODI",
            "PLC"
         ]
      },
      {
         "value":"PFM",
         "synonyms":[
            "PHAPHAMAU",
            "PFM"
         ]
      },
      {
         "value":"FL",
         "synonyms":[
            "PHULERA",
            "FL"
         ]
      },
      {
         "value":"PBE",
         "synonyms":[
            "PILIBHIT",
            "PBE"
         ]
      },
      {
         "value":"PPI",
         "synonyms":[
            "PIPARIYA",
            "PPI"
         ]
      },
      {
         "value":"PTJ",
         "synonyms":[
            "PODANUR",
            "PTJ"
         ]
      },
      {
         "value":"PBR",
         "synonyms":[
            "PORBANDAR",
            "PBR"
         ]
      },
      {
         "value":"PBH",
         "synonyms":[
            "PRATAPGARH",
            "PBH"
         ]
      },
      {
         "value":"PDY",
         "synonyms":[
            "PUDUCHERRY",
            "PDY"
         ]
      },
      {
         "value":"SCL",
         "synonyms":[
            "SILCHAR",
            "SCL"
         ]
      },
      {
         "value":"SHTT",
         "synonyms":[
            "SILGHAT",
            "SHTT"
         ]
      },
      {
         "value":"SGUJ",
         "synonyms":[
            "SILIGURI",
            "SGUJ"
         ]
      },
      {
         "value":"SGUT",
         "synonyms":[
            "SILIGURI TOWN",
            "SGUT"
         ]
      },
      {
         "value":"SGRL",
         "synonyms":[
            "SIMALUGURI SLGR SINGRAULI",
            "SGRL"
         ]
      },
      {
         "value":"SKZR",
         "synonyms":[
            "SIRPUR KAGAZNAGAR",
            "SKZR"
         ]
      },
      {
         "value":"SSA",
         "synonyms":[
            "SIRSA",
            "SSA"
         ]
      },
      {
         "value":"SBZ",
         "synonyms":[
            "SISWA BAZAR",
            "SBZ"
         ]
      },
      {
         "value":"SMI",
         "synonyms":[
            "SITAMARHI",
            "SMI"
         ]
      },
      {
         "value":"SPC",
         "synonyms":[
            "SITAPUR CITY",
            "SPC"
         ]
      },
      {
         "value":"SCC",
         "synonyms":[
            "SITAPUR CANTT",
            "SCC"
         ]
      },
      {
         "value":"SURI",
         "synonyms":[
            "SIURI",
            "SURI"
         ]
      },
      {
         "value":"SV",
         "synonyms":[
            "SIWAN",
            "SV"
         ]
      },
      {
         "value":"SOD",
         "synonyms":[
            "SOJAT ROAD",
            "SOD"
         ]
      },
      {
         "value":"SOL",
         "synonyms":[
            "SOLAN",
            "SOL"
         ]
      },
      {
         "value":"SUR",
         "synonyms":[
            "SOLAPUR",
            "SUR"
         ]
      },
      {
         "value":"SMNH",
         "synonyms":[
            "SOMNATH",
            "SMNH"
         ]
      },
      {
         "value":"SPT",
         "synonyms":[
            "SOMPETA",
            "SPT"
         ]
      },
      {
         "value":"SEE",
         "synonyms":[
            "SONPUR",
            "SEE"
         ]
      },
      {
         "value":"CSMT",
         "synonyms":[
            "SRI CHHATRAPATI SHAHU MAHARAJ",
            "CSMT"
         ]
      },
      {
         "value":"SDGH",
         "synonyms":[
            "SRI DUNGARGARH",
            "SDGH"
         ]
      },
      {
         "value":"SGNR",
         "synonyms":[
            "SRIGANGA NAGAR",
            "SGNR"
         ]
      },
      {
         "value":"CHE",
         "synonyms":[
            "SRIKAKULAM ROAD",
            "CHE"
         ]
      },
      {
         "value":"SSPN",
         "synonyms":[
            "SRI SATHYASAI PRASHANTI NILAYAM",
            "SSPN"
         ]
      },
      {
         "value":"SUJH",
         "synonyms":[
            "SUJANGARH",
            "SUJH"
         ]
      },
      {
         "value":"SLN",
         "synonyms":[
            "SULTANPUR",
            "SLN"
         ]
      },
      {
         "value":"ST",
         "synonyms":[
            "SURAT",
            "ST"
         ]
      },
      {
         "value":"SOG",
         "synonyms":[
            "SURATGARH",
            "SOG"
         ]
      },
      {
         "value":"SL",
         "synonyms":[
            "SURATHKAL",
            "SL"
         ]
      },
      {
         "value":"SUNR",
         "synonyms":[
            "SURENDRA NAGAR",
            "SUNR"
         ]
      },
      {
         "value":"TDD",
         "synonyms":[
            "TADEPALLIGUDEM",
            "TDD"
         ]
      },
      {
         "value":"TBM",
         "synonyms":[
            "TAMBARAM",
            "TBM"
         ]
      },
      {
         "value":"TATA",
         "synonyms":[
            "TATANAGAR",
            "TATA"
         ]
      },
      {
         "value":"TLY",
         "synonyms":[
            "THALASSERY",
            "TLY"
         ]
      },
      {
         "value":"TEL",
         "synonyms":[
            "TENALI",
            "TEL"
         ]
      },
      {
         "value":"TS",
         "synonyms":[
            "TENKASI",
            "TS"
         ]
      },
      {
         "value":"TZTB",
         "synonyms":[
            "TEZPUR",
            "TZTB"
         ]
      },
      {
         "value":"TJ",
         "synonyms":[
            "THANJAVUR",
            "TJ"
         ]
      },
      {
         "value":"TVR",
         "synonyms":[
            "THIRUVARUR",
            "TVR"
         ]
      },
      {
         "value":"TPJ",
         "synonyms":[
            "TIRUCHCHIRAPPALLI JUNCTION",
            "TIRUCHCHIRAPPALLI JN",
            "TPJ"
         ]
      },
      {
         "value":"TCN",
         "synonyms":[
            "TIRUCHENDUR",
            "TCN"
         ]
      },
      {
         "value":"TEN",
         "synonyms":[
            "TIRUNELVELI",
            "TEN"
         ]
      },
      {
         "value":"TPTY",
         "synonyms":[
            "TIRUPATI",
            "TPTY"
         ]
      },
      {
         "value":"TUP",
         "synonyms":[
            "TIRUPPUR",
            "TUP"
         ]
      },
      {
         "value":"TIR",
         "synonyms":[
            "TIRUR",
            "TIR"
         ]
      },
      {
         "value":"TIG",
         "synonyms":[
            "TITLAGARH",
            "TIG"
         ]
      },
      {
         "value":"TCR",
         "synonyms":[
            "THRISUR",
            "TCR"
         ]
      },
      {
         "value":"TVC",
         "synonyms":[
            "THIRUVANANTHAPURAM",
            "TVC"
         ]
      },
      {
         "value":"TNM",
         "synonyms":[
            "TIRUVANNAMALAI",
            "TNM"
         ]
      },
      {
         "value":"TMR",
         "synonyms":[
            "TUMSAR ROAD",
            "TMR"
         ]
      },
      {
         "value":"TDL",
         "synonyms":[
            "TUNDLA",
            "TDL"
         ]
      },
      {
         "value":"TUNI",
         "synonyms":[
            "TUNI",
            "TUNI"
         ]
      },
      {
         "value":"TN",
         "synonyms":[
            "TUTICORIN",
            "TN"
         ]
      },
      {
         "value":"UDZ",
         "synonyms":[
            "UDAIPUR CITY",
            "UDZ"
         ]
      },
      {
         "value":"UHP",
         "synonyms":[
            "UDHAMPUR",
            "UHP"
         ]
      },
      {
         "value":"UDN",
         "synonyms":[
            "UDHNA",
            "UDN"
         ]
      },
      {
         "value":"UD",
         "synonyms":[
            "UDUPI",
            "UD"
         ]
      },
      {
         "value":"UJN",
         "synonyms":[
            "UJJAIN",
            "UJN"
         ]
      },
      {
         "value":"UNA",
         "synonyms":[
            "UNA",
            "UNA"
         ]
      },
      {
         "value":"UCR",
         "synonyms":[
            "UNCHAHAR",
            "UCR"
         ]
      },
      {
         "value":"ON",
         "synonyms":[
            "UNNAO",
            "ON"
         ]
      },
      {
         "value":"BDJ",
         "synonyms":[
            "VADAKARA",
            "BDJ"
         ]
      },
      {
         "value":"BRC",
         "synonyms":[
            "VADODARA",
            "BRC"
         ]
      },
      {
         "value":"BL",
         "synonyms":[
            "VALSAD",
            "BL"
         ]
      },
      {
         "value":"MEJ",
         "synonyms":[
            "VANCHI MANIYACHCHI JUNCTION",
            "VANCHI MANIYACHCHI JN",
            "MEJ"
         ]
      },
      {
         "value":"BSB",
         "synonyms":[
            "VARANASI",
            "BSB"
         ]
      },
      {
         "value":"VAK",
         "synonyms":[
            "VARKALA",
            "VAK"
         ]
      },
      {
         "value":"BSR",
         "synonyms":[
            "VASAI ROAD",
            "BSR"
         ]
      },
      {
         "value":"VSG",
         "synonyms":[
            "VASCO DA GAMA",
            "VSG"
         ]
      },
      {
         "value":"VLKN",
         "synonyms":[
            "VELANKANNI",
            "VLKN"
         ]
      },
      {
         "value":"VRL",
         "synonyms":[
            "VERAVAL",
            "VRL"
         ]
      },
      {
         "value":"BHS",
         "synonyms":[
            "VIDISHA",
            "BHS"
         ]
      },
      {
         "value":"BZA",
         "synonyms":[
            "VIJAYAWADA",
            "BZA"
         ]
      },
      {
         "value":"VM",
         "synonyms":[
            "VILLUPURAM JUNCTION",
            "VILLUPURAM JN",
            "VM"
         ]
      },
      {
         "value":"VG",
         "synonyms":[
            "VIRAMGAM",
            "VG"
         ]
      },
      {
         "value":"VPT",
         "synonyms":[
            "VIRUDUNAGAR JUNCTION",
            "VIRUDUNAGAR JN",
            "VPT"
         ]
      },
      {
         "value":"VSKP",
         "synonyms":[
            "VISAKHAPATNAM",
            "VSKP"
         ]
      },
      {
         "value":"VZM",
         "synonyms":[
            "VIZIANAGARAM",
            "VZM"
         ]
      },
      {
         "value":"VRI",
         "synonyms":[
            "VRIDDHACHALAM JUNCTION",
            "VRIDDHACHALAM JN",
            "VRI"
         ]
      },
      {
         "value":"WADI",
         "synonyms":[
            "WADI",
            "WADI"
         ]
      },
      {
         "value":"WKR",
         "synonyms":[
            "WANKANER",
            "WKR"
         ]
      },
      {
         "value":"WL",
         "synonyms":[
            "WARANGAL",
            "WL"
         ]
      },
      {
         "value":"WR",
         "synonyms":[
            "WARDHA JUNCTION",
            "WARDHA JN",
            "WR"
         ]
      },
      {
         "value":"YPR",
         "synonyms":[
            "YESVANTPUR",
            "YPR"
         ]
      },
      {
         "value":"ZB",
         "synonyms":[
            "ZAFARABAD",
            "ZB"
         ]
      }
   ]
}
}
